# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vcar/Winsurf/nagaspilot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vcar/Winsurf/nagaspilot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vcar/Winsurf/nagaspilot/CMakeFiles /home/vcar/Winsurf/nagaspilot//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vcar/Winsurf/nagaspilot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dummy_target

# Build rule for target.
dummy_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dummy_target
.PHONY : dummy_target

# fast build rule for target.
dummy_target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/build
.PHONY : dummy_target/fast

selfdrive/modeld/models/commonmodel.o: selfdrive/modeld/models/commonmodel.cc.o
.PHONY : selfdrive/modeld/models/commonmodel.o

# target to build an object file
selfdrive/modeld/models/commonmodel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/modeld/models/commonmodel.cc.o
.PHONY : selfdrive/modeld/models/commonmodel.cc.o

selfdrive/modeld/models/commonmodel.i: selfdrive/modeld/models/commonmodel.cc.i
.PHONY : selfdrive/modeld/models/commonmodel.i

# target to preprocess a source file
selfdrive/modeld/models/commonmodel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/modeld/models/commonmodel.cc.i
.PHONY : selfdrive/modeld/models/commonmodel.cc.i

selfdrive/modeld/models/commonmodel.s: selfdrive/modeld/models/commonmodel.cc.s
.PHONY : selfdrive/modeld/models/commonmodel.s

# target to generate assembly for a file
selfdrive/modeld/models/commonmodel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/modeld/models/commonmodel.cc.s
.PHONY : selfdrive/modeld/models/commonmodel.cc.s

selfdrive/modeld/transforms/loadyuv.o: selfdrive/modeld/transforms/loadyuv.cc.o
.PHONY : selfdrive/modeld/transforms/loadyuv.o

# target to build an object file
selfdrive/modeld/transforms/loadyuv.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/modeld/transforms/loadyuv.cc.o
.PHONY : selfdrive/modeld/transforms/loadyuv.cc.o

selfdrive/modeld/transforms/loadyuv.i: selfdrive/modeld/transforms/loadyuv.cc.i
.PHONY : selfdrive/modeld/transforms/loadyuv.i

# target to preprocess a source file
selfdrive/modeld/transforms/loadyuv.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/modeld/transforms/loadyuv.cc.i
.PHONY : selfdrive/modeld/transforms/loadyuv.cc.i

selfdrive/modeld/transforms/loadyuv.s: selfdrive/modeld/transforms/loadyuv.cc.s
.PHONY : selfdrive/modeld/transforms/loadyuv.s

# target to generate assembly for a file
selfdrive/modeld/transforms/loadyuv.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/modeld/transforms/loadyuv.cc.s
.PHONY : selfdrive/modeld/transforms/loadyuv.cc.s

selfdrive/modeld/transforms/transform.o: selfdrive/modeld/transforms/transform.cc.o
.PHONY : selfdrive/modeld/transforms/transform.o

# target to build an object file
selfdrive/modeld/transforms/transform.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/modeld/transforms/transform.cc.o
.PHONY : selfdrive/modeld/transforms/transform.cc.o

selfdrive/modeld/transforms/transform.i: selfdrive/modeld/transforms/transform.cc.i
.PHONY : selfdrive/modeld/transforms/transform.i

# target to preprocess a source file
selfdrive/modeld/transforms/transform.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/modeld/transforms/transform.cc.i
.PHONY : selfdrive/modeld/transforms/transform.cc.i

selfdrive/modeld/transforms/transform.s: selfdrive/modeld/transforms/transform.cc.s
.PHONY : selfdrive/modeld/transforms/transform.s

# target to generate assembly for a file
selfdrive/modeld/transforms/transform.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/modeld/transforms/transform.cc.s
.PHONY : selfdrive/modeld/transforms/transform.cc.s

selfdrive/pandad/can_list_to_can_capnp.o: selfdrive/pandad/can_list_to_can_capnp.cc.o
.PHONY : selfdrive/pandad/can_list_to_can_capnp.o

# target to build an object file
selfdrive/pandad/can_list_to_can_capnp.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/can_list_to_can_capnp.cc.o
.PHONY : selfdrive/pandad/can_list_to_can_capnp.cc.o

selfdrive/pandad/can_list_to_can_capnp.i: selfdrive/pandad/can_list_to_can_capnp.cc.i
.PHONY : selfdrive/pandad/can_list_to_can_capnp.i

# target to preprocess a source file
selfdrive/pandad/can_list_to_can_capnp.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/can_list_to_can_capnp.cc.i
.PHONY : selfdrive/pandad/can_list_to_can_capnp.cc.i

selfdrive/pandad/can_list_to_can_capnp.s: selfdrive/pandad/can_list_to_can_capnp.cc.s
.PHONY : selfdrive/pandad/can_list_to_can_capnp.s

# target to generate assembly for a file
selfdrive/pandad/can_list_to_can_capnp.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/can_list_to_can_capnp.cc.s
.PHONY : selfdrive/pandad/can_list_to_can_capnp.cc.s

selfdrive/pandad/main.o: selfdrive/pandad/main.cc.o
.PHONY : selfdrive/pandad/main.o

# target to build an object file
selfdrive/pandad/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/main.cc.o
.PHONY : selfdrive/pandad/main.cc.o

selfdrive/pandad/main.i: selfdrive/pandad/main.cc.i
.PHONY : selfdrive/pandad/main.i

# target to preprocess a source file
selfdrive/pandad/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/main.cc.i
.PHONY : selfdrive/pandad/main.cc.i

selfdrive/pandad/main.s: selfdrive/pandad/main.cc.s
.PHONY : selfdrive/pandad/main.s

# target to generate assembly for a file
selfdrive/pandad/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/main.cc.s
.PHONY : selfdrive/pandad/main.cc.s

selfdrive/pandad/panda.o: selfdrive/pandad/panda.cc.o
.PHONY : selfdrive/pandad/panda.o

# target to build an object file
selfdrive/pandad/panda.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/panda.cc.o
.PHONY : selfdrive/pandad/panda.cc.o

selfdrive/pandad/panda.i: selfdrive/pandad/panda.cc.i
.PHONY : selfdrive/pandad/panda.i

# target to preprocess a source file
selfdrive/pandad/panda.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/panda.cc.i
.PHONY : selfdrive/pandad/panda.cc.i

selfdrive/pandad/panda.s: selfdrive/pandad/panda.cc.s
.PHONY : selfdrive/pandad/panda.s

# target to generate assembly for a file
selfdrive/pandad/panda.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/panda.cc.s
.PHONY : selfdrive/pandad/panda.cc.s

selfdrive/pandad/panda_comms.o: selfdrive/pandad/panda_comms.cc.o
.PHONY : selfdrive/pandad/panda_comms.o

# target to build an object file
selfdrive/pandad/panda_comms.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/panda_comms.cc.o
.PHONY : selfdrive/pandad/panda_comms.cc.o

selfdrive/pandad/panda_comms.i: selfdrive/pandad/panda_comms.cc.i
.PHONY : selfdrive/pandad/panda_comms.i

# target to preprocess a source file
selfdrive/pandad/panda_comms.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/panda_comms.cc.i
.PHONY : selfdrive/pandad/panda_comms.cc.i

selfdrive/pandad/panda_comms.s: selfdrive/pandad/panda_comms.cc.s
.PHONY : selfdrive/pandad/panda_comms.s

# target to generate assembly for a file
selfdrive/pandad/panda_comms.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/panda_comms.cc.s
.PHONY : selfdrive/pandad/panda_comms.cc.s

selfdrive/pandad/panda_safety.o: selfdrive/pandad/panda_safety.cc.o
.PHONY : selfdrive/pandad/panda_safety.o

# target to build an object file
selfdrive/pandad/panda_safety.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/panda_safety.cc.o
.PHONY : selfdrive/pandad/panda_safety.cc.o

selfdrive/pandad/panda_safety.i: selfdrive/pandad/panda_safety.cc.i
.PHONY : selfdrive/pandad/panda_safety.i

# target to preprocess a source file
selfdrive/pandad/panda_safety.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/panda_safety.cc.i
.PHONY : selfdrive/pandad/panda_safety.cc.i

selfdrive/pandad/panda_safety.s: selfdrive/pandad/panda_safety.cc.s
.PHONY : selfdrive/pandad/panda_safety.s

# target to generate assembly for a file
selfdrive/pandad/panda_safety.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/panda_safety.cc.s
.PHONY : selfdrive/pandad/panda_safety.cc.s

selfdrive/pandad/pandad.o: selfdrive/pandad/pandad.cc.o
.PHONY : selfdrive/pandad/pandad.o

# target to build an object file
selfdrive/pandad/pandad.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/pandad.cc.o
.PHONY : selfdrive/pandad/pandad.cc.o

selfdrive/pandad/pandad.i: selfdrive/pandad/pandad.cc.i
.PHONY : selfdrive/pandad/pandad.i

# target to preprocess a source file
selfdrive/pandad/pandad.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/pandad.cc.i
.PHONY : selfdrive/pandad/pandad.cc.i

selfdrive/pandad/pandad.s: selfdrive/pandad/pandad.cc.s
.PHONY : selfdrive/pandad/pandad.s

# target to generate assembly for a file
selfdrive/pandad/pandad.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/pandad.cc.s
.PHONY : selfdrive/pandad/pandad.cc.s

selfdrive/pandad/spi.o: selfdrive/pandad/spi.cc.o
.PHONY : selfdrive/pandad/spi.o

# target to build an object file
selfdrive/pandad/spi.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/spi.cc.o
.PHONY : selfdrive/pandad/spi.cc.o

selfdrive/pandad/spi.i: selfdrive/pandad/spi.cc.i
.PHONY : selfdrive/pandad/spi.i

# target to preprocess a source file
selfdrive/pandad/spi.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/spi.cc.i
.PHONY : selfdrive/pandad/spi.cc.i

selfdrive/pandad/spi.s: selfdrive/pandad/spi.cc.s
.PHONY : selfdrive/pandad/spi.s

# target to generate assembly for a file
selfdrive/pandad/spi.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/spi.cc.s
.PHONY : selfdrive/pandad/spi.cc.s

selfdrive/pandad/tests/test_pandad_usbprotocol.o: selfdrive/pandad/tests/test_pandad_usbprotocol.cc.o
.PHONY : selfdrive/pandad/tests/test_pandad_usbprotocol.o

# target to build an object file
selfdrive/pandad/tests/test_pandad_usbprotocol.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/tests/test_pandad_usbprotocol.cc.o
.PHONY : selfdrive/pandad/tests/test_pandad_usbprotocol.cc.o

selfdrive/pandad/tests/test_pandad_usbprotocol.i: selfdrive/pandad/tests/test_pandad_usbprotocol.cc.i
.PHONY : selfdrive/pandad/tests/test_pandad_usbprotocol.i

# target to preprocess a source file
selfdrive/pandad/tests/test_pandad_usbprotocol.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/tests/test_pandad_usbprotocol.cc.i
.PHONY : selfdrive/pandad/tests/test_pandad_usbprotocol.cc.i

selfdrive/pandad/tests/test_pandad_usbprotocol.s: selfdrive/pandad/tests/test_pandad_usbprotocol.cc.s
.PHONY : selfdrive/pandad/tests/test_pandad_usbprotocol.s

# target to generate assembly for a file
selfdrive/pandad/tests/test_pandad_usbprotocol.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/pandad/tests/test_pandad_usbprotocol.cc.s
.PHONY : selfdrive/pandad/tests/test_pandad_usbprotocol.cc.s

selfdrive/ui/installer/installer.o: selfdrive/ui/installer/installer.cc.o
.PHONY : selfdrive/ui/installer/installer.o

# target to build an object file
selfdrive/ui/installer/installer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/installer/installer.cc.o
.PHONY : selfdrive/ui/installer/installer.cc.o

selfdrive/ui/installer/installer.i: selfdrive/ui/installer/installer.cc.i
.PHONY : selfdrive/ui/installer/installer.i

# target to preprocess a source file
selfdrive/ui/installer/installer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/installer/installer.cc.i
.PHONY : selfdrive/ui/installer/installer.cc.i

selfdrive/ui/installer/installer.s: selfdrive/ui/installer/installer.cc.s
.PHONY : selfdrive/ui/installer/installer.s

# target to generate assembly for a file
selfdrive/ui/installer/installer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/installer/installer.cc.s
.PHONY : selfdrive/ui/installer/installer.cc.s

selfdrive/ui/main.o: selfdrive/ui/main.cc.o
.PHONY : selfdrive/ui/main.o

# target to build an object file
selfdrive/ui/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/main.cc.o
.PHONY : selfdrive/ui/main.cc.o

selfdrive/ui/main.i: selfdrive/ui/main.cc.i
.PHONY : selfdrive/ui/main.i

# target to preprocess a source file
selfdrive/ui/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/main.cc.i
.PHONY : selfdrive/ui/main.cc.i

selfdrive/ui/main.s: selfdrive/ui/main.cc.s
.PHONY : selfdrive/ui/main.s

# target to generate assembly for a file
selfdrive/ui/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/main.cc.s
.PHONY : selfdrive/ui/main.cc.s

selfdrive/ui/qt/api.o: selfdrive/ui/qt/api.cc.o
.PHONY : selfdrive/ui/qt/api.o

# target to build an object file
selfdrive/ui/qt/api.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/api.cc.o
.PHONY : selfdrive/ui/qt/api.cc.o

selfdrive/ui/qt/api.i: selfdrive/ui/qt/api.cc.i
.PHONY : selfdrive/ui/qt/api.i

# target to preprocess a source file
selfdrive/ui/qt/api.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/api.cc.i
.PHONY : selfdrive/ui/qt/api.cc.i

selfdrive/ui/qt/api.s: selfdrive/ui/qt/api.cc.s
.PHONY : selfdrive/ui/qt/api.s

# target to generate assembly for a file
selfdrive/ui/qt/api.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/api.cc.s
.PHONY : selfdrive/ui/qt/api.cc.s

selfdrive/ui/qt/body.o: selfdrive/ui/qt/body.cc.o
.PHONY : selfdrive/ui/qt/body.o

# target to build an object file
selfdrive/ui/qt/body.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/body.cc.o
.PHONY : selfdrive/ui/qt/body.cc.o

selfdrive/ui/qt/body.i: selfdrive/ui/qt/body.cc.i
.PHONY : selfdrive/ui/qt/body.i

# target to preprocess a source file
selfdrive/ui/qt/body.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/body.cc.i
.PHONY : selfdrive/ui/qt/body.cc.i

selfdrive/ui/qt/body.s: selfdrive/ui/qt/body.cc.s
.PHONY : selfdrive/ui/qt/body.s

# target to generate assembly for a file
selfdrive/ui/qt/body.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/body.cc.s
.PHONY : selfdrive/ui/qt/body.cc.s

selfdrive/ui/qt/home.o: selfdrive/ui/qt/home.cc.o
.PHONY : selfdrive/ui/qt/home.o

# target to build an object file
selfdrive/ui/qt/home.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/home.cc.o
.PHONY : selfdrive/ui/qt/home.cc.o

selfdrive/ui/qt/home.i: selfdrive/ui/qt/home.cc.i
.PHONY : selfdrive/ui/qt/home.i

# target to preprocess a source file
selfdrive/ui/qt/home.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/home.cc.i
.PHONY : selfdrive/ui/qt/home.cc.i

selfdrive/ui/qt/home.s: selfdrive/ui/qt/home.cc.s
.PHONY : selfdrive/ui/qt/home.s

# target to generate assembly for a file
selfdrive/ui/qt/home.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/home.cc.s
.PHONY : selfdrive/ui/qt/home.cc.s

selfdrive/ui/qt/network/networking.o: selfdrive/ui/qt/network/networking.cc.o
.PHONY : selfdrive/ui/qt/network/networking.o

# target to build an object file
selfdrive/ui/qt/network/networking.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/network/networking.cc.o
.PHONY : selfdrive/ui/qt/network/networking.cc.o

selfdrive/ui/qt/network/networking.i: selfdrive/ui/qt/network/networking.cc.i
.PHONY : selfdrive/ui/qt/network/networking.i

# target to preprocess a source file
selfdrive/ui/qt/network/networking.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/network/networking.cc.i
.PHONY : selfdrive/ui/qt/network/networking.cc.i

selfdrive/ui/qt/network/networking.s: selfdrive/ui/qt/network/networking.cc.s
.PHONY : selfdrive/ui/qt/network/networking.s

# target to generate assembly for a file
selfdrive/ui/qt/network/networking.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/network/networking.cc.s
.PHONY : selfdrive/ui/qt/network/networking.cc.s

selfdrive/ui/qt/network/wifi_manager.o: selfdrive/ui/qt/network/wifi_manager.cc.o
.PHONY : selfdrive/ui/qt/network/wifi_manager.o

# target to build an object file
selfdrive/ui/qt/network/wifi_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/network/wifi_manager.cc.o
.PHONY : selfdrive/ui/qt/network/wifi_manager.cc.o

selfdrive/ui/qt/network/wifi_manager.i: selfdrive/ui/qt/network/wifi_manager.cc.i
.PHONY : selfdrive/ui/qt/network/wifi_manager.i

# target to preprocess a source file
selfdrive/ui/qt/network/wifi_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/network/wifi_manager.cc.i
.PHONY : selfdrive/ui/qt/network/wifi_manager.cc.i

selfdrive/ui/qt/network/wifi_manager.s: selfdrive/ui/qt/network/wifi_manager.cc.s
.PHONY : selfdrive/ui/qt/network/wifi_manager.s

# target to generate assembly for a file
selfdrive/ui/qt/network/wifi_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/network/wifi_manager.cc.s
.PHONY : selfdrive/ui/qt/network/wifi_manager.cc.s

selfdrive/ui/qt/offroad/developer_panel.o: selfdrive/ui/qt/offroad/developer_panel.cc.o
.PHONY : selfdrive/ui/qt/offroad/developer_panel.o

# target to build an object file
selfdrive/ui/qt/offroad/developer_panel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/developer_panel.cc.o
.PHONY : selfdrive/ui/qt/offroad/developer_panel.cc.o

selfdrive/ui/qt/offroad/developer_panel.i: selfdrive/ui/qt/offroad/developer_panel.cc.i
.PHONY : selfdrive/ui/qt/offroad/developer_panel.i

# target to preprocess a source file
selfdrive/ui/qt/offroad/developer_panel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/developer_panel.cc.i
.PHONY : selfdrive/ui/qt/offroad/developer_panel.cc.i

selfdrive/ui/qt/offroad/developer_panel.s: selfdrive/ui/qt/offroad/developer_panel.cc.s
.PHONY : selfdrive/ui/qt/offroad/developer_panel.s

# target to generate assembly for a file
selfdrive/ui/qt/offroad/developer_panel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/developer_panel.cc.s
.PHONY : selfdrive/ui/qt/offroad/developer_panel.cc.s

selfdrive/ui/qt/offroad/driverview.o: selfdrive/ui/qt/offroad/driverview.cc.o
.PHONY : selfdrive/ui/qt/offroad/driverview.o

# target to build an object file
selfdrive/ui/qt/offroad/driverview.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/driverview.cc.o
.PHONY : selfdrive/ui/qt/offroad/driverview.cc.o

selfdrive/ui/qt/offroad/driverview.i: selfdrive/ui/qt/offroad/driverview.cc.i
.PHONY : selfdrive/ui/qt/offroad/driverview.i

# target to preprocess a source file
selfdrive/ui/qt/offroad/driverview.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/driverview.cc.i
.PHONY : selfdrive/ui/qt/offroad/driverview.cc.i

selfdrive/ui/qt/offroad/driverview.s: selfdrive/ui/qt/offroad/driverview.cc.s
.PHONY : selfdrive/ui/qt/offroad/driverview.s

# target to generate assembly for a file
selfdrive/ui/qt/offroad/driverview.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/driverview.cc.s
.PHONY : selfdrive/ui/qt/offroad/driverview.cc.s

selfdrive/ui/qt/offroad/experimental_mode.o: selfdrive/ui/qt/offroad/experimental_mode.cc.o
.PHONY : selfdrive/ui/qt/offroad/experimental_mode.o

# target to build an object file
selfdrive/ui/qt/offroad/experimental_mode.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/experimental_mode.cc.o
.PHONY : selfdrive/ui/qt/offroad/experimental_mode.cc.o

selfdrive/ui/qt/offroad/experimental_mode.i: selfdrive/ui/qt/offroad/experimental_mode.cc.i
.PHONY : selfdrive/ui/qt/offroad/experimental_mode.i

# target to preprocess a source file
selfdrive/ui/qt/offroad/experimental_mode.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/experimental_mode.cc.i
.PHONY : selfdrive/ui/qt/offroad/experimental_mode.cc.i

selfdrive/ui/qt/offroad/experimental_mode.s: selfdrive/ui/qt/offroad/experimental_mode.cc.s
.PHONY : selfdrive/ui/qt/offroad/experimental_mode.s

# target to generate assembly for a file
selfdrive/ui/qt/offroad/experimental_mode.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/experimental_mode.cc.s
.PHONY : selfdrive/ui/qt/offroad/experimental_mode.cc.s

selfdrive/ui/qt/offroad/model_selector.o: selfdrive/ui/qt/offroad/model_selector.cc.o
.PHONY : selfdrive/ui/qt/offroad/model_selector.o

# target to build an object file
selfdrive/ui/qt/offroad/model_selector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/model_selector.cc.o
.PHONY : selfdrive/ui/qt/offroad/model_selector.cc.o

selfdrive/ui/qt/offroad/model_selector.i: selfdrive/ui/qt/offroad/model_selector.cc.i
.PHONY : selfdrive/ui/qt/offroad/model_selector.i

# target to preprocess a source file
selfdrive/ui/qt/offroad/model_selector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/model_selector.cc.i
.PHONY : selfdrive/ui/qt/offroad/model_selector.cc.i

selfdrive/ui/qt/offroad/model_selector.s: selfdrive/ui/qt/offroad/model_selector.cc.s
.PHONY : selfdrive/ui/qt/offroad/model_selector.s

# target to generate assembly for a file
selfdrive/ui/qt/offroad/model_selector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/model_selector.cc.s
.PHONY : selfdrive/ui/qt/offroad/model_selector.cc.s

selfdrive/ui/qt/offroad/np_panel.o: selfdrive/ui/qt/offroad/np_panel.cc.o
.PHONY : selfdrive/ui/qt/offroad/np_panel.o

# target to build an object file
selfdrive/ui/qt/offroad/np_panel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/np_panel.cc.o
.PHONY : selfdrive/ui/qt/offroad/np_panel.cc.o

selfdrive/ui/qt/offroad/np_panel.i: selfdrive/ui/qt/offroad/np_panel.cc.i
.PHONY : selfdrive/ui/qt/offroad/np_panel.i

# target to preprocess a source file
selfdrive/ui/qt/offroad/np_panel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/np_panel.cc.i
.PHONY : selfdrive/ui/qt/offroad/np_panel.cc.i

selfdrive/ui/qt/offroad/np_panel.s: selfdrive/ui/qt/offroad/np_panel.cc.s
.PHONY : selfdrive/ui/qt/offroad/np_panel.s

# target to generate assembly for a file
selfdrive/ui/qt/offroad/np_panel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/np_panel.cc.s
.PHONY : selfdrive/ui/qt/offroad/np_panel.cc.s

selfdrive/ui/qt/offroad/onboarding.o: selfdrive/ui/qt/offroad/onboarding.cc.o
.PHONY : selfdrive/ui/qt/offroad/onboarding.o

# target to build an object file
selfdrive/ui/qt/offroad/onboarding.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/onboarding.cc.o
.PHONY : selfdrive/ui/qt/offroad/onboarding.cc.o

selfdrive/ui/qt/offroad/onboarding.i: selfdrive/ui/qt/offroad/onboarding.cc.i
.PHONY : selfdrive/ui/qt/offroad/onboarding.i

# target to preprocess a source file
selfdrive/ui/qt/offroad/onboarding.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/onboarding.cc.i
.PHONY : selfdrive/ui/qt/offroad/onboarding.cc.i

selfdrive/ui/qt/offroad/onboarding.s: selfdrive/ui/qt/offroad/onboarding.cc.s
.PHONY : selfdrive/ui/qt/offroad/onboarding.s

# target to generate assembly for a file
selfdrive/ui/qt/offroad/onboarding.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/onboarding.cc.s
.PHONY : selfdrive/ui/qt/offroad/onboarding.cc.s

selfdrive/ui/qt/offroad/settings.o: selfdrive/ui/qt/offroad/settings.cc.o
.PHONY : selfdrive/ui/qt/offroad/settings.o

# target to build an object file
selfdrive/ui/qt/offroad/settings.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/settings.cc.o
.PHONY : selfdrive/ui/qt/offroad/settings.cc.o

selfdrive/ui/qt/offroad/settings.i: selfdrive/ui/qt/offroad/settings.cc.i
.PHONY : selfdrive/ui/qt/offroad/settings.i

# target to preprocess a source file
selfdrive/ui/qt/offroad/settings.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/settings.cc.i
.PHONY : selfdrive/ui/qt/offroad/settings.cc.i

selfdrive/ui/qt/offroad/settings.s: selfdrive/ui/qt/offroad/settings.cc.s
.PHONY : selfdrive/ui/qt/offroad/settings.s

# target to generate assembly for a file
selfdrive/ui/qt/offroad/settings.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/settings.cc.s
.PHONY : selfdrive/ui/qt/offroad/settings.cc.s

selfdrive/ui/qt/offroad/software_settings.o: selfdrive/ui/qt/offroad/software_settings.cc.o
.PHONY : selfdrive/ui/qt/offroad/software_settings.o

# target to build an object file
selfdrive/ui/qt/offroad/software_settings.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/software_settings.cc.o
.PHONY : selfdrive/ui/qt/offroad/software_settings.cc.o

selfdrive/ui/qt/offroad/software_settings.i: selfdrive/ui/qt/offroad/software_settings.cc.i
.PHONY : selfdrive/ui/qt/offroad/software_settings.i

# target to preprocess a source file
selfdrive/ui/qt/offroad/software_settings.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/software_settings.cc.i
.PHONY : selfdrive/ui/qt/offroad/software_settings.cc.i

selfdrive/ui/qt/offroad/software_settings.s: selfdrive/ui/qt/offroad/software_settings.cc.s
.PHONY : selfdrive/ui/qt/offroad/software_settings.s

# target to generate assembly for a file
selfdrive/ui/qt/offroad/software_settings.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/offroad/software_settings.cc.s
.PHONY : selfdrive/ui/qt/offroad/software_settings.cc.s

selfdrive/ui/qt/onroad/alerts.o: selfdrive/ui/qt/onroad/alerts.cc.o
.PHONY : selfdrive/ui/qt/onroad/alerts.o

# target to build an object file
selfdrive/ui/qt/onroad/alerts.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/alerts.cc.o
.PHONY : selfdrive/ui/qt/onroad/alerts.cc.o

selfdrive/ui/qt/onroad/alerts.i: selfdrive/ui/qt/onroad/alerts.cc.i
.PHONY : selfdrive/ui/qt/onroad/alerts.i

# target to preprocess a source file
selfdrive/ui/qt/onroad/alerts.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/alerts.cc.i
.PHONY : selfdrive/ui/qt/onroad/alerts.cc.i

selfdrive/ui/qt/onroad/alerts.s: selfdrive/ui/qt/onroad/alerts.cc.s
.PHONY : selfdrive/ui/qt/onroad/alerts.s

# target to generate assembly for a file
selfdrive/ui/qt/onroad/alerts.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/alerts.cc.s
.PHONY : selfdrive/ui/qt/onroad/alerts.cc.s

selfdrive/ui/qt/onroad/annotated_camera.o: selfdrive/ui/qt/onroad/annotated_camera.cc.o
.PHONY : selfdrive/ui/qt/onroad/annotated_camera.o

# target to build an object file
selfdrive/ui/qt/onroad/annotated_camera.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/annotated_camera.cc.o
.PHONY : selfdrive/ui/qt/onroad/annotated_camera.cc.o

selfdrive/ui/qt/onroad/annotated_camera.i: selfdrive/ui/qt/onroad/annotated_camera.cc.i
.PHONY : selfdrive/ui/qt/onroad/annotated_camera.i

# target to preprocess a source file
selfdrive/ui/qt/onroad/annotated_camera.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/annotated_camera.cc.i
.PHONY : selfdrive/ui/qt/onroad/annotated_camera.cc.i

selfdrive/ui/qt/onroad/annotated_camera.s: selfdrive/ui/qt/onroad/annotated_camera.cc.s
.PHONY : selfdrive/ui/qt/onroad/annotated_camera.s

# target to generate assembly for a file
selfdrive/ui/qt/onroad/annotated_camera.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/annotated_camera.cc.s
.PHONY : selfdrive/ui/qt/onroad/annotated_camera.cc.s

selfdrive/ui/qt/onroad/buttons.o: selfdrive/ui/qt/onroad/buttons.cc.o
.PHONY : selfdrive/ui/qt/onroad/buttons.o

# target to build an object file
selfdrive/ui/qt/onroad/buttons.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/buttons.cc.o
.PHONY : selfdrive/ui/qt/onroad/buttons.cc.o

selfdrive/ui/qt/onroad/buttons.i: selfdrive/ui/qt/onroad/buttons.cc.i
.PHONY : selfdrive/ui/qt/onroad/buttons.i

# target to preprocess a source file
selfdrive/ui/qt/onroad/buttons.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/buttons.cc.i
.PHONY : selfdrive/ui/qt/onroad/buttons.cc.i

selfdrive/ui/qt/onroad/buttons.s: selfdrive/ui/qt/onroad/buttons.cc.s
.PHONY : selfdrive/ui/qt/onroad/buttons.s

# target to generate assembly for a file
selfdrive/ui/qt/onroad/buttons.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/buttons.cc.s
.PHONY : selfdrive/ui/qt/onroad/buttons.cc.s

selfdrive/ui/qt/onroad/driver_monitoring.o: selfdrive/ui/qt/onroad/driver_monitoring.cc.o
.PHONY : selfdrive/ui/qt/onroad/driver_monitoring.o

# target to build an object file
selfdrive/ui/qt/onroad/driver_monitoring.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/driver_monitoring.cc.o
.PHONY : selfdrive/ui/qt/onroad/driver_monitoring.cc.o

selfdrive/ui/qt/onroad/driver_monitoring.i: selfdrive/ui/qt/onroad/driver_monitoring.cc.i
.PHONY : selfdrive/ui/qt/onroad/driver_monitoring.i

# target to preprocess a source file
selfdrive/ui/qt/onroad/driver_monitoring.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/driver_monitoring.cc.i
.PHONY : selfdrive/ui/qt/onroad/driver_monitoring.cc.i

selfdrive/ui/qt/onroad/driver_monitoring.s: selfdrive/ui/qt/onroad/driver_monitoring.cc.s
.PHONY : selfdrive/ui/qt/onroad/driver_monitoring.s

# target to generate assembly for a file
selfdrive/ui/qt/onroad/driver_monitoring.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/driver_monitoring.cc.s
.PHONY : selfdrive/ui/qt/onroad/driver_monitoring.cc.s

selfdrive/ui/qt/onroad/hud.o: selfdrive/ui/qt/onroad/hud.cc.o
.PHONY : selfdrive/ui/qt/onroad/hud.o

# target to build an object file
selfdrive/ui/qt/onroad/hud.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/hud.cc.o
.PHONY : selfdrive/ui/qt/onroad/hud.cc.o

selfdrive/ui/qt/onroad/hud.i: selfdrive/ui/qt/onroad/hud.cc.i
.PHONY : selfdrive/ui/qt/onroad/hud.i

# target to preprocess a source file
selfdrive/ui/qt/onroad/hud.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/hud.cc.i
.PHONY : selfdrive/ui/qt/onroad/hud.cc.i

selfdrive/ui/qt/onroad/hud.s: selfdrive/ui/qt/onroad/hud.cc.s
.PHONY : selfdrive/ui/qt/onroad/hud.s

# target to generate assembly for a file
selfdrive/ui/qt/onroad/hud.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/hud.cc.s
.PHONY : selfdrive/ui/qt/onroad/hud.cc.s

selfdrive/ui/qt/onroad/model.o: selfdrive/ui/qt/onroad/model.cc.o
.PHONY : selfdrive/ui/qt/onroad/model.o

# target to build an object file
selfdrive/ui/qt/onroad/model.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/model.cc.o
.PHONY : selfdrive/ui/qt/onroad/model.cc.o

selfdrive/ui/qt/onroad/model.i: selfdrive/ui/qt/onroad/model.cc.i
.PHONY : selfdrive/ui/qt/onroad/model.i

# target to preprocess a source file
selfdrive/ui/qt/onroad/model.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/model.cc.i
.PHONY : selfdrive/ui/qt/onroad/model.cc.i

selfdrive/ui/qt/onroad/model.s: selfdrive/ui/qt/onroad/model.cc.s
.PHONY : selfdrive/ui/qt/onroad/model.s

# target to generate assembly for a file
selfdrive/ui/qt/onroad/model.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/model.cc.s
.PHONY : selfdrive/ui/qt/onroad/model.cc.s

selfdrive/ui/qt/onroad/onroad_home.o: selfdrive/ui/qt/onroad/onroad_home.cc.o
.PHONY : selfdrive/ui/qt/onroad/onroad_home.o

# target to build an object file
selfdrive/ui/qt/onroad/onroad_home.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/onroad_home.cc.o
.PHONY : selfdrive/ui/qt/onroad/onroad_home.cc.o

selfdrive/ui/qt/onroad/onroad_home.i: selfdrive/ui/qt/onroad/onroad_home.cc.i
.PHONY : selfdrive/ui/qt/onroad/onroad_home.i

# target to preprocess a source file
selfdrive/ui/qt/onroad/onroad_home.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/onroad_home.cc.i
.PHONY : selfdrive/ui/qt/onroad/onroad_home.cc.i

selfdrive/ui/qt/onroad/onroad_home.s: selfdrive/ui/qt/onroad/onroad_home.cc.s
.PHONY : selfdrive/ui/qt/onroad/onroad_home.s

# target to generate assembly for a file
selfdrive/ui/qt/onroad/onroad_home.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/onroad/onroad_home.cc.s
.PHONY : selfdrive/ui/qt/onroad/onroad_home.cc.s

selfdrive/ui/qt/prime_state.o: selfdrive/ui/qt/prime_state.cc.o
.PHONY : selfdrive/ui/qt/prime_state.o

# target to build an object file
selfdrive/ui/qt/prime_state.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/prime_state.cc.o
.PHONY : selfdrive/ui/qt/prime_state.cc.o

selfdrive/ui/qt/prime_state.i: selfdrive/ui/qt/prime_state.cc.i
.PHONY : selfdrive/ui/qt/prime_state.i

# target to preprocess a source file
selfdrive/ui/qt/prime_state.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/prime_state.cc.i
.PHONY : selfdrive/ui/qt/prime_state.cc.i

selfdrive/ui/qt/prime_state.s: selfdrive/ui/qt/prime_state.cc.s
.PHONY : selfdrive/ui/qt/prime_state.s

# target to generate assembly for a file
selfdrive/ui/qt/prime_state.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/prime_state.cc.s
.PHONY : selfdrive/ui/qt/prime_state.cc.s

selfdrive/ui/qt/qt_window.o: selfdrive/ui/qt/qt_window.cc.o
.PHONY : selfdrive/ui/qt/qt_window.o

# target to build an object file
selfdrive/ui/qt/qt_window.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/qt_window.cc.o
.PHONY : selfdrive/ui/qt/qt_window.cc.o

selfdrive/ui/qt/qt_window.i: selfdrive/ui/qt/qt_window.cc.i
.PHONY : selfdrive/ui/qt/qt_window.i

# target to preprocess a source file
selfdrive/ui/qt/qt_window.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/qt_window.cc.i
.PHONY : selfdrive/ui/qt/qt_window.cc.i

selfdrive/ui/qt/qt_window.s: selfdrive/ui/qt/qt_window.cc.s
.PHONY : selfdrive/ui/qt/qt_window.s

# target to generate assembly for a file
selfdrive/ui/qt/qt_window.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/qt_window.cc.s
.PHONY : selfdrive/ui/qt/qt_window.cc.s

selfdrive/ui/qt/request_repeater.o: selfdrive/ui/qt/request_repeater.cc.o
.PHONY : selfdrive/ui/qt/request_repeater.o

# target to build an object file
selfdrive/ui/qt/request_repeater.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/request_repeater.cc.o
.PHONY : selfdrive/ui/qt/request_repeater.cc.o

selfdrive/ui/qt/request_repeater.i: selfdrive/ui/qt/request_repeater.cc.i
.PHONY : selfdrive/ui/qt/request_repeater.i

# target to preprocess a source file
selfdrive/ui/qt/request_repeater.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/request_repeater.cc.i
.PHONY : selfdrive/ui/qt/request_repeater.cc.i

selfdrive/ui/qt/request_repeater.s: selfdrive/ui/qt/request_repeater.cc.s
.PHONY : selfdrive/ui/qt/request_repeater.s

# target to generate assembly for a file
selfdrive/ui/qt/request_repeater.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/request_repeater.cc.s
.PHONY : selfdrive/ui/qt/request_repeater.cc.s

selfdrive/ui/qt/setup/reset.o: selfdrive/ui/qt/setup/reset.cc.o
.PHONY : selfdrive/ui/qt/setup/reset.o

# target to build an object file
selfdrive/ui/qt/setup/reset.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/setup/reset.cc.o
.PHONY : selfdrive/ui/qt/setup/reset.cc.o

selfdrive/ui/qt/setup/reset.i: selfdrive/ui/qt/setup/reset.cc.i
.PHONY : selfdrive/ui/qt/setup/reset.i

# target to preprocess a source file
selfdrive/ui/qt/setup/reset.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/setup/reset.cc.i
.PHONY : selfdrive/ui/qt/setup/reset.cc.i

selfdrive/ui/qt/setup/reset.s: selfdrive/ui/qt/setup/reset.cc.s
.PHONY : selfdrive/ui/qt/setup/reset.s

# target to generate assembly for a file
selfdrive/ui/qt/setup/reset.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/setup/reset.cc.s
.PHONY : selfdrive/ui/qt/setup/reset.cc.s

selfdrive/ui/qt/setup/setup.o: selfdrive/ui/qt/setup/setup.cc.o
.PHONY : selfdrive/ui/qt/setup/setup.o

# target to build an object file
selfdrive/ui/qt/setup/setup.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/setup/setup.cc.o
.PHONY : selfdrive/ui/qt/setup/setup.cc.o

selfdrive/ui/qt/setup/setup.i: selfdrive/ui/qt/setup/setup.cc.i
.PHONY : selfdrive/ui/qt/setup/setup.i

# target to preprocess a source file
selfdrive/ui/qt/setup/setup.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/setup/setup.cc.i
.PHONY : selfdrive/ui/qt/setup/setup.cc.i

selfdrive/ui/qt/setup/setup.s: selfdrive/ui/qt/setup/setup.cc.s
.PHONY : selfdrive/ui/qt/setup/setup.s

# target to generate assembly for a file
selfdrive/ui/qt/setup/setup.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/setup/setup.cc.s
.PHONY : selfdrive/ui/qt/setup/setup.cc.s

selfdrive/ui/qt/setup/updater.o: selfdrive/ui/qt/setup/updater.cc.o
.PHONY : selfdrive/ui/qt/setup/updater.o

# target to build an object file
selfdrive/ui/qt/setup/updater.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/setup/updater.cc.o
.PHONY : selfdrive/ui/qt/setup/updater.cc.o

selfdrive/ui/qt/setup/updater.i: selfdrive/ui/qt/setup/updater.cc.i
.PHONY : selfdrive/ui/qt/setup/updater.i

# target to preprocess a source file
selfdrive/ui/qt/setup/updater.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/setup/updater.cc.i
.PHONY : selfdrive/ui/qt/setup/updater.cc.i

selfdrive/ui/qt/setup/updater.s: selfdrive/ui/qt/setup/updater.cc.s
.PHONY : selfdrive/ui/qt/setup/updater.s

# target to generate assembly for a file
selfdrive/ui/qt/setup/updater.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/setup/updater.cc.s
.PHONY : selfdrive/ui/qt/setup/updater.cc.s

selfdrive/ui/qt/sidebar.o: selfdrive/ui/qt/sidebar.cc.o
.PHONY : selfdrive/ui/qt/sidebar.o

# target to build an object file
selfdrive/ui/qt/sidebar.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/sidebar.cc.o
.PHONY : selfdrive/ui/qt/sidebar.cc.o

selfdrive/ui/qt/sidebar.i: selfdrive/ui/qt/sidebar.cc.i
.PHONY : selfdrive/ui/qt/sidebar.i

# target to preprocess a source file
selfdrive/ui/qt/sidebar.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/sidebar.cc.i
.PHONY : selfdrive/ui/qt/sidebar.cc.i

selfdrive/ui/qt/sidebar.s: selfdrive/ui/qt/sidebar.cc.s
.PHONY : selfdrive/ui/qt/sidebar.s

# target to generate assembly for a file
selfdrive/ui/qt/sidebar.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/sidebar.cc.s
.PHONY : selfdrive/ui/qt/sidebar.cc.s

selfdrive/ui/qt/util.o: selfdrive/ui/qt/util.cc.o
.PHONY : selfdrive/ui/qt/util.o

# target to build an object file
selfdrive/ui/qt/util.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/util.cc.o
.PHONY : selfdrive/ui/qt/util.cc.o

selfdrive/ui/qt/util.i: selfdrive/ui/qt/util.cc.i
.PHONY : selfdrive/ui/qt/util.i

# target to preprocess a source file
selfdrive/ui/qt/util.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/util.cc.i
.PHONY : selfdrive/ui/qt/util.cc.i

selfdrive/ui/qt/util.s: selfdrive/ui/qt/util.cc.s
.PHONY : selfdrive/ui/qt/util.s

# target to generate assembly for a file
selfdrive/ui/qt/util.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/util.cc.s
.PHONY : selfdrive/ui/qt/util.cc.s

selfdrive/ui/qt/widgets/cameraview.o: selfdrive/ui/qt/widgets/cameraview.cc.o
.PHONY : selfdrive/ui/qt/widgets/cameraview.o

# target to build an object file
selfdrive/ui/qt/widgets/cameraview.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/cameraview.cc.o
.PHONY : selfdrive/ui/qt/widgets/cameraview.cc.o

selfdrive/ui/qt/widgets/cameraview.i: selfdrive/ui/qt/widgets/cameraview.cc.i
.PHONY : selfdrive/ui/qt/widgets/cameraview.i

# target to preprocess a source file
selfdrive/ui/qt/widgets/cameraview.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/cameraview.cc.i
.PHONY : selfdrive/ui/qt/widgets/cameraview.cc.i

selfdrive/ui/qt/widgets/cameraview.s: selfdrive/ui/qt/widgets/cameraview.cc.s
.PHONY : selfdrive/ui/qt/widgets/cameraview.s

# target to generate assembly for a file
selfdrive/ui/qt/widgets/cameraview.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/cameraview.cc.s
.PHONY : selfdrive/ui/qt/widgets/cameraview.cc.s

selfdrive/ui/qt/widgets/controls.o: selfdrive/ui/qt/widgets/controls.cc.o
.PHONY : selfdrive/ui/qt/widgets/controls.o

# target to build an object file
selfdrive/ui/qt/widgets/controls.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/controls.cc.o
.PHONY : selfdrive/ui/qt/widgets/controls.cc.o

selfdrive/ui/qt/widgets/controls.i: selfdrive/ui/qt/widgets/controls.cc.i
.PHONY : selfdrive/ui/qt/widgets/controls.i

# target to preprocess a source file
selfdrive/ui/qt/widgets/controls.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/controls.cc.i
.PHONY : selfdrive/ui/qt/widgets/controls.cc.i

selfdrive/ui/qt/widgets/controls.s: selfdrive/ui/qt/widgets/controls.cc.s
.PHONY : selfdrive/ui/qt/widgets/controls.s

# target to generate assembly for a file
selfdrive/ui/qt/widgets/controls.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/controls.cc.s
.PHONY : selfdrive/ui/qt/widgets/controls.cc.s

selfdrive/ui/qt/widgets/input.o: selfdrive/ui/qt/widgets/input.cc.o
.PHONY : selfdrive/ui/qt/widgets/input.o

# target to build an object file
selfdrive/ui/qt/widgets/input.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/input.cc.o
.PHONY : selfdrive/ui/qt/widgets/input.cc.o

selfdrive/ui/qt/widgets/input.i: selfdrive/ui/qt/widgets/input.cc.i
.PHONY : selfdrive/ui/qt/widgets/input.i

# target to preprocess a source file
selfdrive/ui/qt/widgets/input.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/input.cc.i
.PHONY : selfdrive/ui/qt/widgets/input.cc.i

selfdrive/ui/qt/widgets/input.s: selfdrive/ui/qt/widgets/input.cc.s
.PHONY : selfdrive/ui/qt/widgets/input.s

# target to generate assembly for a file
selfdrive/ui/qt/widgets/input.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/input.cc.s
.PHONY : selfdrive/ui/qt/widgets/input.cc.s

selfdrive/ui/qt/widgets/keyboard.o: selfdrive/ui/qt/widgets/keyboard.cc.o
.PHONY : selfdrive/ui/qt/widgets/keyboard.o

# target to build an object file
selfdrive/ui/qt/widgets/keyboard.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/keyboard.cc.o
.PHONY : selfdrive/ui/qt/widgets/keyboard.cc.o

selfdrive/ui/qt/widgets/keyboard.i: selfdrive/ui/qt/widgets/keyboard.cc.i
.PHONY : selfdrive/ui/qt/widgets/keyboard.i

# target to preprocess a source file
selfdrive/ui/qt/widgets/keyboard.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/keyboard.cc.i
.PHONY : selfdrive/ui/qt/widgets/keyboard.cc.i

selfdrive/ui/qt/widgets/keyboard.s: selfdrive/ui/qt/widgets/keyboard.cc.s
.PHONY : selfdrive/ui/qt/widgets/keyboard.s

# target to generate assembly for a file
selfdrive/ui/qt/widgets/keyboard.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/keyboard.cc.s
.PHONY : selfdrive/ui/qt/widgets/keyboard.cc.s

selfdrive/ui/qt/widgets/offroad_alerts.o: selfdrive/ui/qt/widgets/offroad_alerts.cc.o
.PHONY : selfdrive/ui/qt/widgets/offroad_alerts.o

# target to build an object file
selfdrive/ui/qt/widgets/offroad_alerts.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/offroad_alerts.cc.o
.PHONY : selfdrive/ui/qt/widgets/offroad_alerts.cc.o

selfdrive/ui/qt/widgets/offroad_alerts.i: selfdrive/ui/qt/widgets/offroad_alerts.cc.i
.PHONY : selfdrive/ui/qt/widgets/offroad_alerts.i

# target to preprocess a source file
selfdrive/ui/qt/widgets/offroad_alerts.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/offroad_alerts.cc.i
.PHONY : selfdrive/ui/qt/widgets/offroad_alerts.cc.i

selfdrive/ui/qt/widgets/offroad_alerts.s: selfdrive/ui/qt/widgets/offroad_alerts.cc.s
.PHONY : selfdrive/ui/qt/widgets/offroad_alerts.s

# target to generate assembly for a file
selfdrive/ui/qt/widgets/offroad_alerts.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/offroad_alerts.cc.s
.PHONY : selfdrive/ui/qt/widgets/offroad_alerts.cc.s

selfdrive/ui/qt/widgets/prime.o: selfdrive/ui/qt/widgets/prime.cc.o
.PHONY : selfdrive/ui/qt/widgets/prime.o

# target to build an object file
selfdrive/ui/qt/widgets/prime.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/prime.cc.o
.PHONY : selfdrive/ui/qt/widgets/prime.cc.o

selfdrive/ui/qt/widgets/prime.i: selfdrive/ui/qt/widgets/prime.cc.i
.PHONY : selfdrive/ui/qt/widgets/prime.i

# target to preprocess a source file
selfdrive/ui/qt/widgets/prime.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/prime.cc.i
.PHONY : selfdrive/ui/qt/widgets/prime.cc.i

selfdrive/ui/qt/widgets/prime.s: selfdrive/ui/qt/widgets/prime.cc.s
.PHONY : selfdrive/ui/qt/widgets/prime.s

# target to generate assembly for a file
selfdrive/ui/qt/widgets/prime.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/prime.cc.s
.PHONY : selfdrive/ui/qt/widgets/prime.cc.s

selfdrive/ui/qt/widgets/scrollview.o: selfdrive/ui/qt/widgets/scrollview.cc.o
.PHONY : selfdrive/ui/qt/widgets/scrollview.o

# target to build an object file
selfdrive/ui/qt/widgets/scrollview.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/scrollview.cc.o
.PHONY : selfdrive/ui/qt/widgets/scrollview.cc.o

selfdrive/ui/qt/widgets/scrollview.i: selfdrive/ui/qt/widgets/scrollview.cc.i
.PHONY : selfdrive/ui/qt/widgets/scrollview.i

# target to preprocess a source file
selfdrive/ui/qt/widgets/scrollview.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/scrollview.cc.i
.PHONY : selfdrive/ui/qt/widgets/scrollview.cc.i

selfdrive/ui/qt/widgets/scrollview.s: selfdrive/ui/qt/widgets/scrollview.cc.s
.PHONY : selfdrive/ui/qt/widgets/scrollview.s

# target to generate assembly for a file
selfdrive/ui/qt/widgets/scrollview.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/scrollview.cc.s
.PHONY : selfdrive/ui/qt/widgets/scrollview.cc.s

selfdrive/ui/qt/widgets/ssh_keys.o: selfdrive/ui/qt/widgets/ssh_keys.cc.o
.PHONY : selfdrive/ui/qt/widgets/ssh_keys.o

# target to build an object file
selfdrive/ui/qt/widgets/ssh_keys.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/ssh_keys.cc.o
.PHONY : selfdrive/ui/qt/widgets/ssh_keys.cc.o

selfdrive/ui/qt/widgets/ssh_keys.i: selfdrive/ui/qt/widgets/ssh_keys.cc.i
.PHONY : selfdrive/ui/qt/widgets/ssh_keys.i

# target to preprocess a source file
selfdrive/ui/qt/widgets/ssh_keys.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/ssh_keys.cc.i
.PHONY : selfdrive/ui/qt/widgets/ssh_keys.cc.i

selfdrive/ui/qt/widgets/ssh_keys.s: selfdrive/ui/qt/widgets/ssh_keys.cc.s
.PHONY : selfdrive/ui/qt/widgets/ssh_keys.s

# target to generate assembly for a file
selfdrive/ui/qt/widgets/ssh_keys.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/ssh_keys.cc.s
.PHONY : selfdrive/ui/qt/widgets/ssh_keys.cc.s

selfdrive/ui/qt/widgets/toggle.o: selfdrive/ui/qt/widgets/toggle.cc.o
.PHONY : selfdrive/ui/qt/widgets/toggle.o

# target to build an object file
selfdrive/ui/qt/widgets/toggle.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/toggle.cc.o
.PHONY : selfdrive/ui/qt/widgets/toggle.cc.o

selfdrive/ui/qt/widgets/toggle.i: selfdrive/ui/qt/widgets/toggle.cc.i
.PHONY : selfdrive/ui/qt/widgets/toggle.i

# target to preprocess a source file
selfdrive/ui/qt/widgets/toggle.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/toggle.cc.i
.PHONY : selfdrive/ui/qt/widgets/toggle.cc.i

selfdrive/ui/qt/widgets/toggle.s: selfdrive/ui/qt/widgets/toggle.cc.s
.PHONY : selfdrive/ui/qt/widgets/toggle.s

# target to generate assembly for a file
selfdrive/ui/qt/widgets/toggle.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/toggle.cc.s
.PHONY : selfdrive/ui/qt/widgets/toggle.cc.s

selfdrive/ui/qt/widgets/wifi.o: selfdrive/ui/qt/widgets/wifi.cc.o
.PHONY : selfdrive/ui/qt/widgets/wifi.o

# target to build an object file
selfdrive/ui/qt/widgets/wifi.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/wifi.cc.o
.PHONY : selfdrive/ui/qt/widgets/wifi.cc.o

selfdrive/ui/qt/widgets/wifi.i: selfdrive/ui/qt/widgets/wifi.cc.i
.PHONY : selfdrive/ui/qt/widgets/wifi.i

# target to preprocess a source file
selfdrive/ui/qt/widgets/wifi.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/wifi.cc.i
.PHONY : selfdrive/ui/qt/widgets/wifi.cc.i

selfdrive/ui/qt/widgets/wifi.s: selfdrive/ui/qt/widgets/wifi.cc.s
.PHONY : selfdrive/ui/qt/widgets/wifi.s

# target to generate assembly for a file
selfdrive/ui/qt/widgets/wifi.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/widgets/wifi.cc.s
.PHONY : selfdrive/ui/qt/widgets/wifi.cc.s

selfdrive/ui/qt/window.o: selfdrive/ui/qt/window.cc.o
.PHONY : selfdrive/ui/qt/window.o

# target to build an object file
selfdrive/ui/qt/window.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/window.cc.o
.PHONY : selfdrive/ui/qt/window.cc.o

selfdrive/ui/qt/window.i: selfdrive/ui/qt/window.cc.i
.PHONY : selfdrive/ui/qt/window.i

# target to preprocess a source file
selfdrive/ui/qt/window.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/window.cc.i
.PHONY : selfdrive/ui/qt/window.cc.i

selfdrive/ui/qt/window.s: selfdrive/ui/qt/window.cc.s
.PHONY : selfdrive/ui/qt/window.s

# target to generate assembly for a file
selfdrive/ui/qt/window.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/qt/window.cc.s
.PHONY : selfdrive/ui/qt/window.cc.s

selfdrive/ui/tests/test_runner.o: selfdrive/ui/tests/test_runner.cc.o
.PHONY : selfdrive/ui/tests/test_runner.o

# target to build an object file
selfdrive/ui/tests/test_runner.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/tests/test_runner.cc.o
.PHONY : selfdrive/ui/tests/test_runner.cc.o

selfdrive/ui/tests/test_runner.i: selfdrive/ui/tests/test_runner.cc.i
.PHONY : selfdrive/ui/tests/test_runner.i

# target to preprocess a source file
selfdrive/ui/tests/test_runner.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/tests/test_runner.cc.i
.PHONY : selfdrive/ui/tests/test_runner.cc.i

selfdrive/ui/tests/test_runner.s: selfdrive/ui/tests/test_runner.cc.s
.PHONY : selfdrive/ui/tests/test_runner.s

# target to generate assembly for a file
selfdrive/ui/tests/test_runner.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/tests/test_runner.cc.s
.PHONY : selfdrive/ui/tests/test_runner.cc.s

selfdrive/ui/tests/test_translations.o: selfdrive/ui/tests/test_translations.cc.o
.PHONY : selfdrive/ui/tests/test_translations.o

# target to build an object file
selfdrive/ui/tests/test_translations.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/tests/test_translations.cc.o
.PHONY : selfdrive/ui/tests/test_translations.cc.o

selfdrive/ui/tests/test_translations.i: selfdrive/ui/tests/test_translations.cc.i
.PHONY : selfdrive/ui/tests/test_translations.i

# target to preprocess a source file
selfdrive/ui/tests/test_translations.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/tests/test_translations.cc.i
.PHONY : selfdrive/ui/tests/test_translations.cc.i

selfdrive/ui/tests/test_translations.s: selfdrive/ui/tests/test_translations.cc.s
.PHONY : selfdrive/ui/tests/test_translations.s

# target to generate assembly for a file
selfdrive/ui/tests/test_translations.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/tests/test_translations.cc.s
.PHONY : selfdrive/ui/tests/test_translations.cc.s

selfdrive/ui/ui.o: selfdrive/ui/ui.cc.o
.PHONY : selfdrive/ui/ui.o

# target to build an object file
selfdrive/ui/ui.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/ui.cc.o
.PHONY : selfdrive/ui/ui.cc.o

selfdrive/ui/ui.i: selfdrive/ui/ui.cc.i
.PHONY : selfdrive/ui/ui.i

# target to preprocess a source file
selfdrive/ui/ui.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/ui.cc.i
.PHONY : selfdrive/ui/ui.cc.i

selfdrive/ui/ui.s: selfdrive/ui/ui.cc.s
.PHONY : selfdrive/ui/ui.s

# target to generate assembly for a file
selfdrive/ui/ui.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/ui.cc.s
.PHONY : selfdrive/ui/ui.cc.s

selfdrive/ui/watch3.o: selfdrive/ui/watch3.cc.o
.PHONY : selfdrive/ui/watch3.o

# target to build an object file
selfdrive/ui/watch3.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/watch3.cc.o
.PHONY : selfdrive/ui/watch3.cc.o

selfdrive/ui/watch3.i: selfdrive/ui/watch3.cc.i
.PHONY : selfdrive/ui/watch3.i

# target to preprocess a source file
selfdrive/ui/watch3.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/watch3.cc.i
.PHONY : selfdrive/ui/watch3.cc.i

selfdrive/ui/watch3.s: selfdrive/ui/watch3.cc.s
.PHONY : selfdrive/ui/watch3.s

# target to generate assembly for a file
selfdrive/ui/watch3.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy_target.dir/build.make CMakeFiles/dummy_target.dir/selfdrive/ui/watch3.cc.s
.PHONY : selfdrive/ui/watch3.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dummy_target"
	@echo "... selfdrive/modeld/models/commonmodel.o"
	@echo "... selfdrive/modeld/models/commonmodel.i"
	@echo "... selfdrive/modeld/models/commonmodel.s"
	@echo "... selfdrive/modeld/transforms/loadyuv.o"
	@echo "... selfdrive/modeld/transforms/loadyuv.i"
	@echo "... selfdrive/modeld/transforms/loadyuv.s"
	@echo "... selfdrive/modeld/transforms/transform.o"
	@echo "... selfdrive/modeld/transforms/transform.i"
	@echo "... selfdrive/modeld/transforms/transform.s"
	@echo "... selfdrive/pandad/can_list_to_can_capnp.o"
	@echo "... selfdrive/pandad/can_list_to_can_capnp.i"
	@echo "... selfdrive/pandad/can_list_to_can_capnp.s"
	@echo "... selfdrive/pandad/main.o"
	@echo "... selfdrive/pandad/main.i"
	@echo "... selfdrive/pandad/main.s"
	@echo "... selfdrive/pandad/panda.o"
	@echo "... selfdrive/pandad/panda.i"
	@echo "... selfdrive/pandad/panda.s"
	@echo "... selfdrive/pandad/panda_comms.o"
	@echo "... selfdrive/pandad/panda_comms.i"
	@echo "... selfdrive/pandad/panda_comms.s"
	@echo "... selfdrive/pandad/panda_safety.o"
	@echo "... selfdrive/pandad/panda_safety.i"
	@echo "... selfdrive/pandad/panda_safety.s"
	@echo "... selfdrive/pandad/pandad.o"
	@echo "... selfdrive/pandad/pandad.i"
	@echo "... selfdrive/pandad/pandad.s"
	@echo "... selfdrive/pandad/spi.o"
	@echo "... selfdrive/pandad/spi.i"
	@echo "... selfdrive/pandad/spi.s"
	@echo "... selfdrive/pandad/tests/test_pandad_usbprotocol.o"
	@echo "... selfdrive/pandad/tests/test_pandad_usbprotocol.i"
	@echo "... selfdrive/pandad/tests/test_pandad_usbprotocol.s"
	@echo "... selfdrive/ui/installer/installer.o"
	@echo "... selfdrive/ui/installer/installer.i"
	@echo "... selfdrive/ui/installer/installer.s"
	@echo "... selfdrive/ui/main.o"
	@echo "... selfdrive/ui/main.i"
	@echo "... selfdrive/ui/main.s"
	@echo "... selfdrive/ui/qt/api.o"
	@echo "... selfdrive/ui/qt/api.i"
	@echo "... selfdrive/ui/qt/api.s"
	@echo "... selfdrive/ui/qt/body.o"
	@echo "... selfdrive/ui/qt/body.i"
	@echo "... selfdrive/ui/qt/body.s"
	@echo "... selfdrive/ui/qt/home.o"
	@echo "... selfdrive/ui/qt/home.i"
	@echo "... selfdrive/ui/qt/home.s"
	@echo "... selfdrive/ui/qt/network/networking.o"
	@echo "... selfdrive/ui/qt/network/networking.i"
	@echo "... selfdrive/ui/qt/network/networking.s"
	@echo "... selfdrive/ui/qt/network/wifi_manager.o"
	@echo "... selfdrive/ui/qt/network/wifi_manager.i"
	@echo "... selfdrive/ui/qt/network/wifi_manager.s"
	@echo "... selfdrive/ui/qt/offroad/developer_panel.o"
	@echo "... selfdrive/ui/qt/offroad/developer_panel.i"
	@echo "... selfdrive/ui/qt/offroad/developer_panel.s"
	@echo "... selfdrive/ui/qt/offroad/driverview.o"
	@echo "... selfdrive/ui/qt/offroad/driverview.i"
	@echo "... selfdrive/ui/qt/offroad/driverview.s"
	@echo "... selfdrive/ui/qt/offroad/experimental_mode.o"
	@echo "... selfdrive/ui/qt/offroad/experimental_mode.i"
	@echo "... selfdrive/ui/qt/offroad/experimental_mode.s"
	@echo "... selfdrive/ui/qt/offroad/model_selector.o"
	@echo "... selfdrive/ui/qt/offroad/model_selector.i"
	@echo "... selfdrive/ui/qt/offroad/model_selector.s"
	@echo "... selfdrive/ui/qt/offroad/np_panel.o"
	@echo "... selfdrive/ui/qt/offroad/np_panel.i"
	@echo "... selfdrive/ui/qt/offroad/np_panel.s"
	@echo "... selfdrive/ui/qt/offroad/onboarding.o"
	@echo "... selfdrive/ui/qt/offroad/onboarding.i"
	@echo "... selfdrive/ui/qt/offroad/onboarding.s"
	@echo "... selfdrive/ui/qt/offroad/settings.o"
	@echo "... selfdrive/ui/qt/offroad/settings.i"
	@echo "... selfdrive/ui/qt/offroad/settings.s"
	@echo "... selfdrive/ui/qt/offroad/software_settings.o"
	@echo "... selfdrive/ui/qt/offroad/software_settings.i"
	@echo "... selfdrive/ui/qt/offroad/software_settings.s"
	@echo "... selfdrive/ui/qt/onroad/alerts.o"
	@echo "... selfdrive/ui/qt/onroad/alerts.i"
	@echo "... selfdrive/ui/qt/onroad/alerts.s"
	@echo "... selfdrive/ui/qt/onroad/annotated_camera.o"
	@echo "... selfdrive/ui/qt/onroad/annotated_camera.i"
	@echo "... selfdrive/ui/qt/onroad/annotated_camera.s"
	@echo "... selfdrive/ui/qt/onroad/buttons.o"
	@echo "... selfdrive/ui/qt/onroad/buttons.i"
	@echo "... selfdrive/ui/qt/onroad/buttons.s"
	@echo "... selfdrive/ui/qt/onroad/driver_monitoring.o"
	@echo "... selfdrive/ui/qt/onroad/driver_monitoring.i"
	@echo "... selfdrive/ui/qt/onroad/driver_monitoring.s"
	@echo "... selfdrive/ui/qt/onroad/hud.o"
	@echo "... selfdrive/ui/qt/onroad/hud.i"
	@echo "... selfdrive/ui/qt/onroad/hud.s"
	@echo "... selfdrive/ui/qt/onroad/model.o"
	@echo "... selfdrive/ui/qt/onroad/model.i"
	@echo "... selfdrive/ui/qt/onroad/model.s"
	@echo "... selfdrive/ui/qt/onroad/onroad_home.o"
	@echo "... selfdrive/ui/qt/onroad/onroad_home.i"
	@echo "... selfdrive/ui/qt/onroad/onroad_home.s"
	@echo "... selfdrive/ui/qt/prime_state.o"
	@echo "... selfdrive/ui/qt/prime_state.i"
	@echo "... selfdrive/ui/qt/prime_state.s"
	@echo "... selfdrive/ui/qt/qt_window.o"
	@echo "... selfdrive/ui/qt/qt_window.i"
	@echo "... selfdrive/ui/qt/qt_window.s"
	@echo "... selfdrive/ui/qt/request_repeater.o"
	@echo "... selfdrive/ui/qt/request_repeater.i"
	@echo "... selfdrive/ui/qt/request_repeater.s"
	@echo "... selfdrive/ui/qt/setup/reset.o"
	@echo "... selfdrive/ui/qt/setup/reset.i"
	@echo "... selfdrive/ui/qt/setup/reset.s"
	@echo "... selfdrive/ui/qt/setup/setup.o"
	@echo "... selfdrive/ui/qt/setup/setup.i"
	@echo "... selfdrive/ui/qt/setup/setup.s"
	@echo "... selfdrive/ui/qt/setup/updater.o"
	@echo "... selfdrive/ui/qt/setup/updater.i"
	@echo "... selfdrive/ui/qt/setup/updater.s"
	@echo "... selfdrive/ui/qt/sidebar.o"
	@echo "... selfdrive/ui/qt/sidebar.i"
	@echo "... selfdrive/ui/qt/sidebar.s"
	@echo "... selfdrive/ui/qt/util.o"
	@echo "... selfdrive/ui/qt/util.i"
	@echo "... selfdrive/ui/qt/util.s"
	@echo "... selfdrive/ui/qt/widgets/cameraview.o"
	@echo "... selfdrive/ui/qt/widgets/cameraview.i"
	@echo "... selfdrive/ui/qt/widgets/cameraview.s"
	@echo "... selfdrive/ui/qt/widgets/controls.o"
	@echo "... selfdrive/ui/qt/widgets/controls.i"
	@echo "... selfdrive/ui/qt/widgets/controls.s"
	@echo "... selfdrive/ui/qt/widgets/input.o"
	@echo "... selfdrive/ui/qt/widgets/input.i"
	@echo "... selfdrive/ui/qt/widgets/input.s"
	@echo "... selfdrive/ui/qt/widgets/keyboard.o"
	@echo "... selfdrive/ui/qt/widgets/keyboard.i"
	@echo "... selfdrive/ui/qt/widgets/keyboard.s"
	@echo "... selfdrive/ui/qt/widgets/offroad_alerts.o"
	@echo "... selfdrive/ui/qt/widgets/offroad_alerts.i"
	@echo "... selfdrive/ui/qt/widgets/offroad_alerts.s"
	@echo "... selfdrive/ui/qt/widgets/prime.o"
	@echo "... selfdrive/ui/qt/widgets/prime.i"
	@echo "... selfdrive/ui/qt/widgets/prime.s"
	@echo "... selfdrive/ui/qt/widgets/scrollview.o"
	@echo "... selfdrive/ui/qt/widgets/scrollview.i"
	@echo "... selfdrive/ui/qt/widgets/scrollview.s"
	@echo "... selfdrive/ui/qt/widgets/ssh_keys.o"
	@echo "... selfdrive/ui/qt/widgets/ssh_keys.i"
	@echo "... selfdrive/ui/qt/widgets/ssh_keys.s"
	@echo "... selfdrive/ui/qt/widgets/toggle.o"
	@echo "... selfdrive/ui/qt/widgets/toggle.i"
	@echo "... selfdrive/ui/qt/widgets/toggle.s"
	@echo "... selfdrive/ui/qt/widgets/wifi.o"
	@echo "... selfdrive/ui/qt/widgets/wifi.i"
	@echo "... selfdrive/ui/qt/widgets/wifi.s"
	@echo "... selfdrive/ui/qt/window.o"
	@echo "... selfdrive/ui/qt/window.i"
	@echo "... selfdrive/ui/qt/window.s"
	@echo "... selfdrive/ui/tests/test_runner.o"
	@echo "... selfdrive/ui/tests/test_runner.i"
	@echo "... selfdrive/ui/tests/test_runner.s"
	@echo "... selfdrive/ui/tests/test_translations.o"
	@echo "... selfdrive/ui/tests/test_translations.i"
	@echo "... selfdrive/ui/tests/test_translations.s"
	@echo "... selfdrive/ui/ui.o"
	@echo "... selfdrive/ui/ui.i"
	@echo "... selfdrive/ui/ui.s"
	@echo "... selfdrive/ui/watch3.o"
	@echo "... selfdrive/ui/watch3.i"
	@echo "... selfdrive/ui/watch3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

